theme: jekyll-theme-minimal
title: temoki.com
description: iOS/Android App Developer in 🇯🇵

# Optional
logo: assets/profile.jpg
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
