theme: jekyll-theme-minimal
title: temoki.com
#description: [A short description of your site's purpose]

# Optional
logo: assets/profile.jpg
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
